### ISSUE TITLE
Plugin not working with ionic's capacitor

### ISSUE THREAD

**Issue by bb1** [kolbasa/cordova-plugin-apkupdater#45] opened 2022-06-17 15:48 UTC
It crashes because the strings `android:label="@string/app_name"` can not be resolved from the generated `android/app/src/main/res/xml/config.xml` file. It seems like this alias is not supported by capacitor. :/

**Comment by kolbasa** [comment] 2022-06-17 17:10
No problem. I actively make sure that everything works.

However, I cannot reproduce this. I have now created two empty projects. A pure Capacitor project and a Capacitor+Ionic project. Both are working for me.

My steps with Capacitor:
```bash
# creating new capacitor project
cap init app test.app.id --web-dir www

# with a black package.json
npm init -y

# and a simple index.html
mkdir www
echo '<html><head></head></html>' > www/index.html

# adding apkupdater plugin
npm install cordova-plugin-apkupdater

# adding android platform
npm install @capacitor/android
cap add android

# deploying app
cap run android
```

My steps with Capacitor + Ionic:
```bash
# creating new capacitor + ionic project
ionic start app blank --type=angular --capacitor --no-interactive

# navigating to app project folder
cd app

# adding apkupdater plugin
npm install cordova-plugin-apkupdater

# adding android platform
ionic capacitor add android

# deploying app
ionic capacitor run android
```

A few questions that come to mind:
- Can you give me the full error message?
- When does the message appear? When launching the app?
- Capacitor Version?

**Comment by mtournay** [comment] 2023-04-20 16:26
Hi Kolbasa

Same issue in my project, when building apk with gradle

```
> Task :app:extractReleaseNativeSymbolTables
Unable to extract native debug metadata from android\app\build\intermediates\merged_native_libs\release\out\lib\arm64-v8a\libtoolChecker.so because unable to locate the objcopy executable for the arm64-v8a ABI.
Unable to extract native debug metadata from android\app\build\intermediates\merged_native_libs\release\out\lib\armeabi-v7a\libtoolChecker.so because unable to locate the objcopy executable for the armeabi-v7a ABI.
Unable to extract native debug metadata from android\app\build\intermediates\merged_native_libs\release\out\lib\x86\libtoolChecker.so because unable to locate the objcopy executable for the x86 ABI.
Unable to extract native debug metadata from android\app\build\intermediates\merged_native_libs\release\out\lib\x86_64\libtoolChecker.so because unable to locate the objcopy executable for the x86_64 ABI.
```

```
* What went wrong:
Execution failed for task ':capacitor-cordova-android-plugins:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\sources\gestionStockApp2\android\capacitor-cordova-android-plugins\src\main\AndroidManifest.xml:9:1-14:12: AAPT: error: resource string/app_name (aka capacitor.android.plugins:string/app_name) not found.

     ERROR:C:\sources\gestionStockApp2\android\capacitor-cordova-android-plugins\src\main\AndroidManifest.xml:15:1-19:12: AAPT: error: resource string/app_name (aka capacitor.android.plugins:string/app_name) not found.
```

without your plugin, everything buid. When testing on android device, your plugin works great (`ionic capacitor run android -l --external`)

build process :
```
call ionic build
if %errorlevel% NEQ 0 GOTO error

call npx cap copy
if %errorlevel% NEQ 0 GOTO error

call npx cap sync
if %errorlevel% NEQ 0 GOTO error

cd %localdir%\Android
call gradlew.bat build
```

I hope those explanations may help you finding the issue

**Comment by mtournay** [comment] 2023-04-20 18:43
btw

```
λ npm --version
8.19.2
λ ionic -v
6.20.8
λ npx capacitor --version
4.7.3
```
this could help
not revelant I think : i'm building a react app

**Comment by kolbasa** [comment] 2023-04-20 19:15
Thanks for the detailed description. Now I understand what the problem is.
I will push a fix in the next couple of days.

**Comment by kolbasa** [comment] 2023-04-21 09:24
I pushed an update. Should work now.

 :+1:

**Comment by mtournay** [comment] 2023-04-21 11:39
It's working ! thanks a lot
You can close this issue.

**Closed** 2023-04-21 11:40 UTC
