### ISSUE TITLE
Root Install Function Returning Error

### ISSUE THREAD

**Issue by Jack-Drake** [kolbasa/cordova-plugin-apkupdater#55] opened 2024-06-17 18:21 UTC
I am having a problem with rootinstall function. This is the error I am getting:
`{"message":"Root command failed: su: invalid uid/gid '-c'","stack":"de.kolbasa.apkupdater.exceptions.RootException\n  at de.kolbasa.apkupdater.tools.ApkInstaller.rootInstall(ApkInstaller.java:120)\n  at de.kolbasa.apkupdater.ApkUpdater.rootInstall(ApkUpdater.java:195)\n  at de.kolbasa.apkupdater.ApkUpdater.lambda$execute$13$de-kolbasa-apkupdater-ApkUpdater(ApkUpdater.java:258)\n  at de.kolbasa.apkupdater.ApkUpdater$$ExternalSyntheticLambda9.run(Unknown Source:4)\n  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n  at java.lang.Thread.run(Thread.java:923)\nCaused by: de.kolbasa.apkupdater.exceptions.InstallationFailedException: su: invalid uid/gid '-c'\n  at de.kolbasa.apkupdater.tools.ApkInstaller.rootInstall(ApkInstaller.java:117)\n  ... 6 more\n"}`

I have verified that I the device is rooted. Any reason why it is returning this error?

**Comment by kolbasa** [comment] 2024-06-17 18:47
I took a quick look at the problem.
[Here](https://github.com/kolbasa/cordova-plugin-apkupdater/blob/feeb7f1b7357dbc2d35d8e2d016911c30e3ce832/src/android/tools/ApkInstaller.java#L99) is the problematic line.
This is probably no longer up to date. The `-c` argument has to be replaced by `0` for it to work.

I can't manage to fix it today. I'll get back to you tomorrow.

**Comment by Jack-Drake** [comment] 2024-06-17 18:56
Thanks Kolbasa. Look forward to hearing back from you

**Comment by kolbasa** [comment] 2024-06-18 11:56
I have now tested the function a little.
I cannot reproduce the problem. I thought that maybe a new Android version had broken the code.
On the Android 13 and 14 emulator with Magisk it still works without any problems.
But I am also not an expert when it comes to rooting devices. So I have to rely on users to provide me with information.

* Which device/emulator do you use?
* What version of Android is it?
* How was the device rooted? Any particular rooting app?
* Does my method `isDeviceRooted()` return `true` for you?

Can you connect the device to your PC and post the output of the following command: 
```
adb shell "su -h"
```

I get the following output:
```
MagiskSU

Usage: su [options] [-] [user [argument...]]

Options:
  -c, --command COMMAND         Pass COMMAND to the invoked shell
  -g, --group GROUP             Specify the primary group
  -G, --supp-group GROUP        Specify a supplementary group.
                                The first specified supplementary group is also used
                                as a primary group if the option -g is not specified.
  -Z, --context CONTEXT         Change SELinux context
  -t, --target PID              PID to take mount namespace from
  -h, --help                    Display this help message and exit
  -, -l, --login                Pretend the shell to be a login shell
  -m, -p,
  --preserve-environment        Preserve the entire environment
  -s, --shell SHELL             Use SHELL instead of the default /system/bin/sh
  -v, --version                 Display version number and exit
  -V                            Display version code and exit
  -mm, -M,
  --mount-master                Force run in the global mount namespace
```

I pushed a fix based on your error message, but I can't test if it solves the problem.
You can install it as follows:

```
cordova plugin add https://github.com/kolbasa/cordova-plugin-apkupdater.git#55-root-install-function-returning-error
```

**Comment by Jack-Drake** [comment] 2024-06-18 16:50
Thank you for getting back to me so quick.
Let me try the fix based on the message I gave you.

It is a tablet, unsure what brand its more of an off brand device. Android 11 is the version. The device customs as a custom ROM and does not need to be rooted manually. As for the function, yes it does return true when asked whether it is rooted.

**Comment by Jack-Drake** [comment] 2024-06-18 17:44
Alright so something new I do not know whether this is directly related to the plugin or something but even when I installed your sample application it returned the same error. But this is the latest error:

`{
  "message": "Root command failed: su: failed to exec pm install -r -d '/data/data/com.sampleAPP.app/files/update/10006.apk' && am start -n com.sampleAPP.app/com.sampleAPP.app.MainActivity: No such file or directory",
  "stack": "de.kolbasa.apkupdater.exceptions.RootException\n  at de.kolbasa.apkupdater.tools.ApkInstaller.rootInstall(ApkInstaller.java:120)\n  at de.kolbasa.apkupdater.ApkUpdater.rootInstall(ApkUpdater.java:195)\n  at de.kolbasa.apkupdater.ApkUpdater.lambda$execute$13$de-kolbasa-apkupdater-ApkUpdater(ApkUpdater.java:258)\n  at de.kolbasa.apkupdater.ApkUpdater$$ExternalSyntheticLambda11.run(D8$$SyntheticClass:0)\n  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n  at java.lang.Thread.run(Thread.java:923)\nCaused by: de.kolbasa.apkupdater.exceptions.InstallationFailedException: su: failed to exec pm install -r -d '/data/data/com.sampleAPP.app/files/update/10006.apk' && am start -n com.sampleAPP.app/com.sampleAPP.app.MainActivity: No such file or directory\n  at de.kolbasa.apkupdater.tools.ApkInstaller.rootInstall(ApkInstaller.java:117)\n  ... 6 more\n"
}`

**Comment by kolbasa** [comment] 2024-06-18 18:07
Can you give me the output of `adb shell "su -h"` (alternatively: `adb shell "su --help"`) ?
The `su` command behaves completely different on your device.

**Comment by Jack-Drake** [comment] 2024-06-18 18:12
Where do i execute this command on the tablet? or on Android Studio?

**Comment by kolbasa** [comment] 2024-06-18 18:17
You can do this in a terminal application of your choice.
For example in Android Studio:

<img width="963" alt="grafik" src="https://github.com/kolbasa/cordova-plugin-apkupdater/assets/3901582/5bbd2fbf-83b6-4254-8314-2e0a9e6e9f8d">

<img width="961" alt="grafik" src="https://github.com/kolbasa/cordova-plugin-apkupdater/assets/3901582/82d149b1-1c99-47a4-aa24-73f974ad94cd">

**Comment by kolbasa** [comment] 2024-06-18 18:25
It may also be possible to simply install the [Magisk](https://github.com/topjohnwu/Magisk) Apk on the device.
This is what I use on the emulator. Magisk installs this `su` application that I use in the plugin.

**Comment by Jack-Drake** [comment] 2024-06-18 19:55
this is the response i got from running the above:

![image](https://github.com/kolbasa/cordova-plugin-apkupdater/assets/44513448/5c65e399-1fed-4fc7-aacc-c4d83d218186)

**Comment by kolbasa** [comment] 2024-06-19 10:45
Hmmm, I don't think I can help any further. For that I would need a device/emulator where I can reproduce the error myself.

The plugin basically does nothing other than execute the installation command `pm install -r -d '/data/data/com.sampleAPP.app/files/update/10006.apk'` with root privileges (`su -c`).

---

Another thing that comes to mind: You may have to enable the authorization for apps on your device first.
I know that Magisk has such an option, where `ADB` **and** `Apps` must be enabled. Perhaps you only have ADB activated.

<img width="406" alt="grafik" src="https://github.com/kolbasa/cordova-plugin-apkupdater/assets/3901582/a7bcbed0-7332-4cee-8d3a-354d66debe46">

---

Furthermore: You could try debugging the command yourself. 
The syntax of the `su` command is different on your device.

You can simply play around with various commands yourself via the `adb shell` until it works.

Before that, however, you must download the update with the ApkUpdater plugin so that it can then be found under `/data/data/com.sampleAPP.app/files/update/10006.apk`.

If you can find the correct syntax, then I would add it.

[Example](https://github.com/kolbasa/cordova-plugin-apkupdater/assets/3901582/bbc17314-7645-475b-9e54-967feb222f46)

---

Or my favorite solution: you manage to install [Magisk](https://github.com/topjohnwu/Magisk) on your device :smiley:.

I will update my documentation. I didn't know that rooted devices could be so different from each other.

**Closed as completed** 2024-11-13 16:26 UTC
