### ISSUE TITLE
Couldn't find meta-data for provider with authority org.app.app.apkupdater.provider

### ISSUE THREAD

**Issue by thomaspalmdk** [kolbasa/cordova-plugin-apkupdater#49] opened 2022-11-21 17:08 UTC
Hi,
I think this happened after I migrated my project to to Android 11 in Cordova 11.
I'm unsure what I need to do to fix this.
After downloading the new APK it fails:

`message: "Couldn't find meta-data for provider with authority org.apporg.appname.apkupdater.provider"`

`stack: "java.lang.IllegalArgumentException\n  at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:662)\n  at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:635)\n  at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:441)\n  at de.kolbasa.apkupdater.tools.ApkInstaller.getUpdate(ApkInstaller.java:32)\n  at de.kolbasa.apkupdater.tools.ApkInstaller.install(ApkInstaller.java:45)\n  at de.kolbasa.apkupdater.ApkUpdater.install(ApkUpdater.java:170)\n  at de.kolbasa.apkupdater.ApkUpdater.lambda$execute$11$de-kolbasa-apkupdater-ApkUpdater(ApkUpdater.java:252)\n  at de.kolbasa.apkupdater.ApkUpdater$$ExternalSyntheticLambda8.run(Unknown Source:4)\n  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n  at java.lang.Thread.run(Thread.java:764)\n"
`

**Comment by kolbasa** [comment] 2022-11-21 18:00
I checked. I can reproduce it on my end as well.

It has probably something to do with the update of `cordova-common`, which was raised to version `4.1.0` 13 days ago.


I probably need to make some adjustments to my `config.xml`.
I'll get back to you in the next few days as soon as I have some time.

**Comment by kolbasa** [comment] 2022-11-21 18:55
I fixed it. 
The change is currently available under:
```
cordova plugin add https://github.com/kolbasa/cordova-plugin-apkupdater#49-cordova11-fix
```
I need to do some testing before I merge it.

**Comment by kolbasa** [comment] 2022-11-23 20:16
Merged

**Closed by kolbasa** 2022-11-23 20:16 UTC

**Comment by capc0** [comment] 2023-01-12 17:02
I am receiving the same error with plugin version 2.6.1 (old and new version of my app running the same version). There was no update to cordova. Is there any explanation for this? Maybe due to a newer Android version on the device?

**Comment by kolbasa** [comment] 2023-01-12 17:27
Can you give me the output of `cordova info` ?
Maybe it is a conflict with another plugin.

**Comment by capc0** [comment] 2023-01-12 17:37
Yeah I also thought so, but there was no plugin update either in the last months that I am aware of.

```
Cordova Packages:

    cli: 11.0.0
        common: 4.1.0
        create: 4.0.0
        lib: 11.0.0
            common: 4.1.0
            fetch: 3.1.0
            serve: 4.0.0

Project Installed Platforms:

    android: 9.1.0

Project Installed Plugins:

    cordova-custom-config: 5.1.1
    cordova-plugin-actionsheet: 2.3.3
    cordova-plugin-androidx-adapter: 1.1.3
    cordova-plugin-androidx: 3.0.0
    cordova-plugin-apkupdater: 2.6.1
    cordova-plugin-app-version: 0.1.14
    cordova-plugin-camera-preview: 0.12.3
    cordova-plugin-camera: 5.0.3
    cordova-plugin-chooser: 1.3.1
    cordova-plugin-device: 2.1.0
    cordova-plugin-dialogs: 2.0.2
    cordova-plugin-email-composer: 0.9.2
    cordova-plugin-enable-multidex: 0.2.0
    cordova-plugin-file-opener2: 2.2.1
    cordova-plugin-file: 6.0.2
    cordova-plugin-firebase-analytics: 5.0.0
    cordova-plugin-firebase-crash: 3.0.0
    cordova-plugin-firebase-messaging: 5.0.1
    cordova-plugin-fullscreen: 1.3.0
    cordova-plugin-geolocation: 4.1.0
    cordova-plugin-inappbrowser: 5.0.0
    cordova-plugin-ionic-keyboard: 2.2.0
    cordova-plugin-ionic-webview: 5.0.0
    cordova-plugin-ios-disableshaketoedit: 1.0.0
    cordova-plugin-network-information: 2.0.2
    cordova-plugin-screen-orientation: 3.0.2
    cordova-plugin-splashscreen: 6.0.2
    cordova-plugin-statusbar: 2.4.3
    cordova-plugin-whitelist: 1.3.5
    cordova-sqlite-storage: 3.4.1
    cordova-support-android-plugin: 1.0.2
    cordova-support-google-services: 1.4.1
    es6-promise-plugin: 4.2.2
    phonegap-plugin-barcodescanner: 8.1.0
    uk.co.workingedge.phonegap.plugin.launchnavigator: 5.0.6

Environment:

    OS: Microsoft Windows 10 Business 10.0.19044 (19044) (Windows 10.0.19044) x64
    Node: v14.21.2
    npm: 6.14.17
```

and this is the relevant part from the `config.xml` (stuff that affects `AndroidManifest.xml`)

```xml
        <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
            <application android:networkSecurityConfig="@xml/network_security_config" />
        </edit-config>
        <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
            <application android:largeHeap="true" />
        </edit-config>
        
        <custom-config-file parent="./application" target="AndroidManifest.xml">
            <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" />
        </custom-config-file>
        ```

**Comment by capc0** [comment] 2023-01-12 17:43
I recently switched node versions via NVM.

If I switch back to my old version, it prints the following info:

```
Cordova Packages:

    cli: 11.0.0
        common: 4.0.2
        create: 4.0.0
        lib: 11.0.0
            common: 4.0.2
            fetch: 3.0.1
            serve: 4.0.0
```

Here cordova common is still 4.0.2.

Not sure why tho 😕

**Comment by kolbasa** [comment] 2023-01-12 18:06
Ah ok. I didn't immediately understand that you were using an older plugin version. Try this:
```
cordova plugin remove cordova-plugin-apkupdater
cordova plugin add https://github.com/kolbasa/cordova-plugin-apkupdater.git#2.6.2
```
I pushed a small change.

**Comment by capc0** [comment] 2023-01-12 18:12
But if the old version of my app uses the 2.6.1 apk-updater logic, it doesnt matter what I install now.
I just have to make sure that the new apk is build with `cordova-common` 4.0.2 instead of 4.1.0, right?

Of course I should update, so that the next release after that can be build with 4.1.0.

**Comment by kolbasa** [comment] 2023-01-12 18:17
Well, I think your old app will still have the working logic.
So that means you just need to make sure that the new update works correctly.
So either you update the ApkUpdater plugin or you manage to get the old plugin version running.

My guess is `cordova-common`, but I honestly couldn`t manage to downgrade the thing.

**Comment by capc0** [comment] 2023-01-12 18:32
Thanks for the information and quick replys! I will update to  `4.0.1`, just wanted to understand the issue at first.
